/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "im.h"


void
im_messenger_3(char *host)
{
	CLIENT *clnt;
	Result_login  *result_1;
	Args_login  login_3_arg;
	Result_getUserRoster  *result_2;
	Session  getuserroster_3_arg;
	Result_getMessagesHistory  *result_3;
	Session  getmessageshistory_3_arg;
	Result_getUnreadMessages  *result_4;
	Session  getunreadmessages_3_arg;
	Status  *result_5;
	Args_sendMessage  sendmessage_3_arg;
	Status  *result_6;
	Args_addUserToRoster  addusertoroster_3_arg;
	Status  *result_7;
	Args_deleteUserFromRoster  deleteuserfromroster_3_arg;
	Result_findUser  *result_8;
	Args_findUser  finduser_3_arg;
	Result_getFriendshipRequests  *result_9;
	Session  getfriendshiprequests_3_arg;
	Status  *result_10;
	Args_register  signup_3_arg;

	//#ifndef	DEBUG
	clnt = clnt_create (host, IM_MESSENGER, VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	//#endif	/* DEBUG */
	/*
	login_3_arg.name  = "admin2";
	login_3_arg.passwd = "admin2";
	result_1 = login_3(&login_3_arg, clnt);
	if (result_1 == (Result_login *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	
	
	/*
	getuserroster_3_arg.id = 2;
	result_2 = getuserroster_3(&getuserroster_3_arg, clnt);
	if (result_2 == (Result_getUserRoster *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	getmessageshistory_3_arg.id = 1;
	result_3 = getmessageshistory_3(&getmessageshistory_3_arg, clnt);
	if (result_3 == (Result_getMessagesHistory *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	getunreadmessages_3_arg.id = 2;
	result_4 = getunreadmessages_3(&getunreadmessages_3_arg, clnt);
	if (result_4 == (Result_getUnreadMessages *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%d\n", result_4->messages.messages_len);
	*/
	/*
	sendmessage_3_arg.session.id = 1;
	sendmessage_3_arg.recipientId = 2;
	sendmessage_3_arg.msg = "I'm fine, too!";
	result_5 = sendmessage_3(&sendmessage_3_arg, clnt);
	if (result_5 == (Status *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	addusertoroster_3_arg.session.id = 1;
	addusertoroster_3_arg.userId = 2;
	result_6 = addusertoroster_3(&addusertoroster_3_arg, clnt);
	if (result_6 == (Status *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	deleteuserfromroster_3_arg.session.id = 1;
	deleteuserfromroster_3_arg.userId = 2;
	result_7 = deleteuserfromroster_3(&deleteuserfromroster_3_arg, clnt);
	if (result_7 == (Status *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	finduser_3_arg.session.id = 1;
	finduser_3_arg.name = "";
	finduser_3_arg.nick = "admin2";
	result_8 = finduser_3(&finduser_3_arg, clnt);
	if (result_8 == (Result_findUser *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
	/*
	getfriendshiprequests_3_arg.id = 2	;
	result_9 = getfriendshiprequests_3(&getfriendshiprequests_3_arg, clnt);
	if (result_9 == (Result_getFriendshipRequests *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	*/
	/*
	signup_3_arg.name = "admin2";
	signup_3_arg.nick = "admin2";
	signup_3_arg.passwd = "admin2";
	result_10 = signup_3(&signup_3_arg, clnt);
	if (result_10 == (Status *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	host = "127.0.0.1";
	im_messenger_3 (host);
exit (0);
}
