/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "im.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

Result_login *
login_3(Args_login *argp, CLIENT *clnt)
{
	static Result_login clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, login,
		(xdrproc_t) xdr_Args_login, (caddr_t) argp,
		(xdrproc_t) xdr_Result_login, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Result_getUserRoster *
getuserroster_3(Session *argp, CLIENT *clnt)
{
	static Result_getUserRoster clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getUserRoster,
		(xdrproc_t) xdr_Session, (caddr_t) argp,
		(xdrproc_t) xdr_Result_getUserRoster, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Result_getMessagesHistory *
getmessageshistory_3(Session *argp, CLIENT *clnt)
{
	static Result_getMessagesHistory clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getMessagesHistory,
		(xdrproc_t) xdr_Session, (caddr_t) argp,
		(xdrproc_t) xdr_Result_getMessagesHistory, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Result_getUnreadMessages *
getunreadmessages_3(Session *argp, CLIENT *clnt)
{
	static Result_getUnreadMessages clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getUnreadMessages,
		(xdrproc_t) xdr_Session, (caddr_t) argp,
		(xdrproc_t) xdr_Result_getUnreadMessages, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Status *
sendmessage_3(Args_sendMessage *argp, CLIENT *clnt)
{
	static Status clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, sendMessage,
		(xdrproc_t) xdr_Args_sendMessage, (caddr_t) argp,
		(xdrproc_t) xdr_Status, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Status *
addusertoroster_3(Args_addUserToRoster *argp, CLIENT *clnt)
{
	static Status clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, addUserToRoster,
		(xdrproc_t) xdr_Args_addUserToRoster, (caddr_t) argp,
		(xdrproc_t) xdr_Status, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Status *
deleteuserfromroster_3(Args_deleteUserFromRoster *argp, CLIENT *clnt)
{
	static Status clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, deleteUserFromRoster,
		(xdrproc_t) xdr_Args_deleteUserFromRoster, (caddr_t) argp,
		(xdrproc_t) xdr_Status, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Result_findUser *
finduser_3(Args_findUser *argp, CLIENT *clnt)
{
	static Result_findUser clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, findUser,
		(xdrproc_t) xdr_Args_findUser, (caddr_t) argp,
		(xdrproc_t) xdr_Result_findUser, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Result_getFriendshipRequests *
getfriendshiprequests_3(Session *argp, CLIENT *clnt)
{
	static Result_getFriendshipRequests clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, getFriendshipRequests,
		(xdrproc_t) xdr_Session, (caddr_t) argp,
		(xdrproc_t) xdr_Result_getFriendshipRequests, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

Status *
signup_3(Args_register *argp, CLIENT *clnt)
{
	static Status clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, signup,
		(xdrproc_t) xdr_Args_register, (caddr_t) argp,
		(xdrproc_t) xdr_Status, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
