DROP TABLE IF EXISTS users, messages, roster, sessions; 

CREATE TABLE users (ID SERIAL PRIMARY KEY,
NAME VARCHAR(32) NOT NULL,
NICK VARCHAR(32) NOT NULL,
PASSWD VARCHAR(32) NOT NULL,
ONLINESTATUS BOOLEAN DEFAULT FALSE,
LAST_ACTION TIMESTAMP NOT NULL);

CREATE TABLE messages (ID SERIAL PRIMARY KEY,
SENDER INTEGER NOT NULL,
RECIPIENT INTEGER NOT NULL,
MESSAGE TEXT,
MSG_READ BOOLEAN DEFAULT FALSE,
DTIME TIMESTAMP NOT NULL);

CREATE TABLE roster (ID SERIAL PRIMARY KEY,
TARGET_USER INTEGER NOT NULL,
ROSTER_USER INTEGER NOT NULL,
TUSTATUS INTEGER NOT NULL,
RUSTATUS INTEGER NOT NULL); -- -1 - removed, 0 - not accepted, 1 - in roaster

CREATE TABLE sessions (ID SERIAL PRIMARY KEY,
USER_ID INTEGER UNIQUE NOT NULL);
